name: Format

on:
  push:
    branches:
      - main
      - dev

jobs:
  format:
    if: github.repository == 'test'
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
